### ISSUE TITLE
Possible to rebuild to update git-secret?

### ISSUE THREAD

**Issue by emacdona** [ncpierson/git-secret#3]
Thank you for making this Dockerfile! Have you thought about re-building and re-publishing the image so that your :latest tag would be using a newer version of git-secret?

You got me past this bug:
https://github.com/sobolevn/git-secret/issues/136

But now I'm dealing with this one:
https://github.com/sobolevn/git-secret/issues/135

Thanks,
Ed

**Comment by florabtw** [comment]
Hey @emacdona that doesn't sound too hard. I'll update it today :)
Give me an hour or two.

**Comment by florabtw** [comment]
Hi @emacdona , can you try now with the `:latest` or `:1.1.0` image? Let me know how it goes!

**Comment by florabtw** [comment]
Hi @emacdona , any updates on this? I'm going to close the issue if I don't hear anything.

**Comment by emacdona** [comment]
Hey @ncpierson -- sorry for the delay in getting back to you. Yes, it worked great. Thank you!
